### ISSUE TITLE
Crash when distance from route is too low

### ISSUE THREAD

**Issue by patrickedelen** [luscus/geojson.lib.routeboxer#3]
Not sure if this can be resolved, but I'm trying to search along a route with RouteBoxer but need a very low distance (.1 KM) for my purposes. It seems that if the distance from the route is too low, the algorithm will try to mark cells that are outside the defined portion of the grid and crash the app.

```
    -- incr x:
    => cell:  [ 10, 4 ]
/node_modules/geojson.lib.routeboxer/lib/geojson.lib.routeboxer.js:391
  this.grid_[x + 1][y - 1] = 1;
                           ^

TypeError: Cannot set property '3' of undefined
    at RouteBoxer.markCell_ (/node_modules/geojson.lib.routeboxer/lib/geojson.lib.routeboxer.js:391:28)
```

Any ideas?

**Comment by cristianb84** [comment]
I have the same issue. Patrick, did u managed to fix it ?

**Comment by patrickedelen** [comment]
I haven't managed to fix it as of yet but I am working on changing the RouteBoxer algorithm implementation so that there are cells outside those that contain the route.

**Comment by luscus** [comment]
Hello everybody,
I did not look into this lib for a long time (doing something else nowadays) but I would like to reactivate it, refactor it and write tests...
Issue #1 and #2 have been fixed (will be committed over the WE) I could look into the precision issue.
Could you provide me your test GeoJSON LineString?

**Comment by patrickedelen** [comment]
Hi @luscus, glad you are revisiting this issue! I ended up switching to using $near and ensuring each point on the PolyLine was a minimum distance apart as the RouteBoxer algorithm takes much longer when dealing with long routes. The code I wrote that uses RouteBoxer is available on my repo but the specific file I have that deals with it is here: https://github.com/patrickedelen/FloodWatch/blob/b64f79dc89208504310298b6debabdf82d24fd1e/FrontEnd/app/route.js . I can grab the LineString if that would help, but as my app takes in many different routes it wouldn't be a really fair test (that and it seemed to crash on every route with a distance of .25 or .1). Thanks!

**Comment by luscus** [comment]
well 0.1 km boxes around a long route: that is intensive...
but testing with route2 (simple.js test) and any distance below 15km shows something very wrong.
My use case was an other one and this  worked with it.
I need to right tests to figure that out.

I will investigate but I can't say how long it will take: I'm doing this on my rare free time

**Comment by luscus** [comment]
the getGridIntersect_ method was calculating completely false  intermediate points to fill the gaps between the waypoints. It only worked for my routes because the waypoints were within the boxer cells and no  intermediate points had to be calculated...
I have Switched to a calculation based on vectors by @chrisveness in the following repo: [geodesy](https://github.com/chrisveness/geodesy)

My whole lib is a mess, I initially planed to use his package as base for the geojson.lib and geojson.lib.routeboxer but it is not modular: Maths should be extracted, different types of calculations also and I would like to work with raw arrays ([x,y,z]) in order separate processing from representation (GeoJSON, Google Maps Objects, ...)
If I find some time I will think of something

At least it is now working with hight precision (even with a  corridor of only 100m)

``` javascript
const RouteBoxer = require('geojson.lib.routeboxer');
const boxer = new RouteBoxer();
const boxes = boxer.box(path, 0.1);
```

**Comment by patrickedelen** [comment]
Thanks for fixing this issue! I've been busy the past few days but glad to see you were able to isolate the problem.
